# permissions for end users to edit ltargets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ltarget-editor-role
rules:
- apiGroups:
  - lz.rexa.god
  resources:
  - ltargets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lz.rexa.god
  resources:
  - ltargets/status
  verbs:
  - get
