# permissions for end users to view ltargets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ltarget-viewer-role
rules:
- apiGroups:
  - lz.rexa.god
  resources:
  - ltargets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - lz.rexa.god
  resources:
  - ltargets/status
  verbs:
  - get
