---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - get
  - watch
- apiGroups:
  - lz.rexa.god
  resources:
  - ltargets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lz.rexa.god
  resources:
  - ltargets/finalizers
  verbs:
  - update
- apiGroups:
  - lz.rexa.god
  resources:
  - ltargets/status
  verbs:
  - get
  - patch
  - update
